# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pa0DgV4qjHU-IkaqK746Zygp1DrBeUV5
"""

import os, json, http.client, urllib.request
from http.cookiejar import MozillaCookieJar

# 加载 cookie
jar = MozillaCookieJar(os.path.expanduser("~/.midway/cookie"))
jar.load(ignore_discard=True, ignore_expires=True)

host = "corp.management-ui.turtle.aws.dev"
path = "/api/admin/v2/roleMappings/search"

# 生成精确的 Cookie 头
req = urllib.request.Request(f"https://{host}{path}")
jar.add_cookie_header(req)
cookie_header = req.get_header("Cookie")

# 组合 headers（以 DevTools 为准）
headers = {
  "Cookie":        cookie_header,
  "Content-Type":  "application/json",
  "Accept":        "application/json",
  "Origin":        "https://corp.management-ui.turtle.aws.dev",
  "Referer":       "https://corp.management-ui.turtle.aws.dev/role-mappings-view",
  # …如果 DevTools 里还有 X-Requested-With、X-CSRF-Token，就一并加上…
}

body = {
  "page": 1,
  "size": 50,
  # …对应 DevTools 里的 JSON …
}

conn = http.client.HTTPSConnection(host)
conn.request("POST", path, body=json.dumps(body), headers=headers)
resp = conn.getresponse()
print(resp.status, resp.reason)
print(resp.read().decode())